.TH PYXSTITCH "1" "<Date>" "pyxstitch <Version>" "User Commands"
.SH NAME
pyxstitch \- code to cross stitch
.SH DESCRIPTION
usage: pyxstitch [\-h] [\-\-file FILE] [\-\-lexer LEXER] [\-\-output OUTPUT]
.IP
[\-\-theme THEME] [\-\-kv N [N ...]]
[\-\-map N [N ...]] [\-\-config CONFIG]
[\-\-multipage MULTIPAGE]
[\-\-format FORMAT]
[\-\-style STYLE]
[\-\-font FONT]
[\-\-version] [\-\-quiet] [\-\-symbols SYMBOLS] [\-\-hszoom HSZOOM]
[\-\-hezoom HEZOOM] [\-\-vszoom VSZOOM] [\-\-vezoom VEZOOM]
.PP
Convert source code files to cross stitch patterns.
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-file\fR FILE
input source code file to create a pattern from.
.TP
\fB\-\-lexer\fR LEXER
the source code lexer to use when reading input and
converting input tokens into colors
.TP
\fB\-\-output\fR OUTPUT
output name
.TP
\fB\-\-theme\fR THEME
pattern theme. indicates the background and symbol
color outputs for the output pattern
.br
\- bw
.br
\- dark
.br
\- dark\-dmc
.br
\- light (default)
.br
\- light\-dmc
.TP
\fB\-\-kv\fR N [N ...]
key/value configuration parameters for setting the
output format
.TP
\fB\-\-map\fR N [N ...]
when selecting colors will map one token color to
another color (override)
.TP
\fB\-\-config\fR CONFIG
configuration file
.TP
\fB\-\-multipage\fR MULTIPAGE
enable multipage output
.br
\- auto (default)
.br
\- off
.br
\- on
.TP
\fB\-\-format\fR FORMAT
output file format
.br
\- jpg
.br
\- pdf
.br
\- png (default)
.br
\- pyxstitch
.TP
\fB\-\-style\fR STYLE
token color styling (from pygments), examples:
.br
\- default (default, uses the default styling)
.br
\- abap
.br
\- algol
.br
\- algol_nu
.br
\- arduino
.br
\- autumn
.br
\- borland
.br
\- colorful
.br
\- emacs
.br
\- friendly
.br
\- lovelace
.br
\- manni
.br
\- monokai
.br
\- murphy
.br
\- paraiso\-dark
.br
\- paraiso\-light
.br
\- pastie
.br
\- perldoc
.br
\- trac
.br
\- rainbow_dash
.TP
\fB\-\-font\fR FONT
font to use for the pattern, available fonts
.br
\- detect (default, attempt to auto-detect font-size)
.br
\- monospace\-ascii\-2x5
.br
\- monospace\-ascii\-3x5
.br
\- monospace\-ascii\-3x7
.br
\- monospace\-ascii\-5x9
.br
\- proportional\-ascii\-3x6
.br
\- proportional\-ascii\-4x7
.TP
\fB\-\-version\fR
display version
.TP
\fB\-\-quiet\fR
less verbose output
.TP
\fB\-\-symbols\fR SYMBOLS
symbol set for stitching symbols
.TP
\fB\-\-hszoom\fR HSZOOM
horizontal start zoom
.TP
\fB\-\-hezoom\fR HEZOOM
horizontal end zoom
.TP
\fB\-\-vszoom\fR VSZOOM
vertical start zoom
.TP
\fB\-\-vezoom\fR VEZOOM
vertical end zoom
